-- Yemek etiketleri (0019).
--
-- Plan üreticisinin filtresi: alerjisi olan bir kullanıcıya gluten içeren
-- yemek, vegan birine peynir önerilemez. Kategori tek başına yetmiyor —
-- "kahvaltı" kategorisinde hem zeytin hem sucuk var.
--
-- `vejetaryen` ve `vegan` ELLE işaretlenmiyor, içeriklerden türetiliyor:
-- hayvansal bir etiket yoksa vegan, yalnızca süt/yumurta varsa vejetaryen.
-- Böylece yeni yemek eklenince tutarsızlık çıkmıyor.
--
-- Etiketler ad ve kategori örüntülerinden üretildi; tek tek gözden geçirilmedi.
-- Yanlış eşleşme görülürse düzeltilmeli (özellikle karışık tarifler).

update public.foods f
set tags = v.tags
from (values
('mercimek corbasi',ARRAY['vegan','vejetaryen']::text[]),
('ezogelin corbasi',ARRAY['vegan','vejetaryen']::text[]),
('yayla corbasi',ARRAY['sut','vejetaryen']::text[]),
('tarhana corbasi',ARRAY['gluten','vegan','vejetaryen']::text[]),
('domates corbasi',ARRAY['vegan','vejetaryen']::text[]),
('tavuk suyu corba',ARRAY['et']::text[]),
('iskembe corbasi',ARRAY['et','sakatat']::text[]),
('dugun corbasi',ARRAY['gluten','vegan','vejetaryen']::text[]),
('brokoli corbasi',ARRAY['vegan','vejetaryen']::text[]),
('mantar corbasi',ARRAY['mantar','vegan','vejetaryen']::text[]),
('anali kizli corba',ARRAY['vegan','vejetaryen']::text[]),
('yogurt corbasi',ARRAY['sut','vejetaryen']::text[]),
('izgara kofte',ARRAY['et','kirmizi_et']::text[]),
('sulu kofte',ARRAY['et','kirmizi_et']::text[]),
('inegol kofte',ARRAY['et','kirmizi_et']::text[]),
('kuru kofte',ARRAY['et','kirmizi_et']::text[]),
('tavuk sis',ARRAY['et']::text[]),
('tavuk izgara',ARRAY['et']::text[]),
('tavuk sote',ARRAY['et']::text[]),
('tavuk pirzola',ARRAY['et','kirmizi_et']::text[]),
('adana kebap',ARRAY['aci','et','kirmizi_et']::text[]),
('urfa kebap',ARRAY['et','kirmizi_et']::text[]),
('beyti kebap',ARRAY['et','kirmizi_et']::text[]),
('iskender kebap',ARRAY['et','kirmizi_et']::text[]),
('doner (et)',ARRAY['et','kirmizi_et']::text[]),
('tavuk doner',ARRAY['et']::text[]),
('kuzu sis',ARRAY['et','kirmizi_et']::text[]),
('kuzu pirzola',ARRAY['et','kirmizi_et']::text[]),
('et sote',ARRAY['et','kirmizi_et']::text[]),
('kavurma',ARRAY['et','kirmizi_et']::text[]),
('tas kebabi',ARRAY['et','kirmizi_et']::text[]),
('hunkar begendi',ARRAY['et','kirmizi_et']::text[]),
('etli turlu',ARRAY['et','kirmizi_et']::text[]),
('karniyarik',ARRAY['et','kirmizi_et']::text[]),
('imambayildi',ARRAY['vegan','vejetaryen']::text[]),
('musakka',ARRAY['et','kirmizi_et']::text[]),
('etli biber dolma',ARRAY['et','kirmizi_et']::text[]),
('zeytinyagli yaprak sarma',ARRAY['vegan','vejetaryen','zeytin']::text[]),
('etli yaprak sarma',ARRAY['et','kirmizi_et']::text[]),
('lahana sarma',ARRAY['vegan','vejetaryen']::text[]),
('kabak dolma',ARRAY['vegan','vejetaryen']::text[]),
('balik izgara',ARRAY['balik','et','yuksek_seker']::text[]),
('hamsi tava',ARRAY['balik','et']::text[]),
('somon izgara',ARRAY['balik','et']::text[]),
('levrek izgara',ARRAY['balik','et']::text[]),
('cupra izgara',ARRAY['balik','et']::text[]),
('palamut izgara',ARRAY['balik','et']::text[]),
('karides guvec',ARRAY['balik','et','kabuklu']::text[]),
('kalamar tava',ARRAY['balik','et','kabuklu']::text[]),
('kuru fasulye',ARRAY['baklagil','vegan','vejetaryen']::text[]),
('nohut yemegi',ARRAY['baklagil','vegan','vejetaryen']::text[]),
('barbunya pilaki',ARRAY['baklagil','vegan','vejetaryen']::text[]),
('mercimek yemegi',ARRAY['baklagil','vegan','vejetaryen']::text[]),
('etli nohut',ARRAY['baklagil','et','kirmizi_et']::text[]),
('bakla yemegi',ARRAY['baklagil','vegan','vejetaryen']::text[]),
('turlu',ARRAY['vegan','vejetaryen']::text[]),
('zeytinyagli taze fasulye',ARRAY['vegan','vejetaryen','zeytin']::text[]),
('zeytinyagli enginar',ARRAY['vegan','vejetaryen','zeytin']::text[]),
('zeytinyagli pirasa',ARRAY['vegan','vejetaryen','zeytin']::text[]),
('ispanak yemegi',ARRAY['vegan','vejetaryen']::text[]),
('kabak yemegi',ARRAY['vegan','vejetaryen']::text[]),
('karnabahar yemegi',ARRAY['vegan','vejetaryen']::text[]),
('bamya yemegi',ARRAY['vegan','vejetaryen']::text[]),
('patlican oturtma',ARRAY['et','kirmizi_et']::text[]),
('mucver',ARRAY['vejetaryen','yumurta']::text[]),
('menemen',ARRAY['vejetaryen','yumurta']::text[]),
('sahanda yumurta',ARRAY['vejetaryen','yumurta']::text[]),
('haslanmis yumurta',ARRAY['vejetaryen','yumurta']::text[]),
('omlet',ARRAY['vejetaryen','yumurta']::text[]),
('sucuklu yumurta',ARRAY['et','kirmizi_et','yumurta']::text[]),
('pirinc pilavi',ARRAY['vegan','vejetaryen']::text[]),
('bulgur pilavi',ARRAY['vegan','vejetaryen']::text[]),
('sehriyeli pilav',ARRAY['gluten','vegan','vejetaryen']::text[]),
('nohutlu pilav',ARRAY['vegan','vejetaryen']::text[]),
('ic pilav',ARRAY['vegan','vejetaryen']::text[]),
('kuskus',ARRAY['gluten','vegan','vejetaryen']::text[]),
('makarna (domates soslu)',ARRAY['gluten','vegan','vejetaryen']::text[]),
('firin makarna',ARRAY['gluten','vegan','vejetaryen']::text[]),
('eriste',ARRAY['gluten','vegan','vejetaryen']::text[]),
('manti',ARRAY['gluten','vegan','vejetaryen']::text[]),
('spagetti bolonez',ARRAY['gluten','vegan','vejetaryen']::text[]),
('beyaz ekmek',ARRAY['gluten','vegan','vejetaryen']::text[]),
('tam bugday ekmegi',ARRAY['gluten','vegan','vejetaryen']::text[]),
('cavdar ekmegi',ARRAY['gluten','vegan','vejetaryen']::text[]),
('simit',ARRAY['gluten','susam','vegan','vejetaryen']::text[]),
('pogaca',ARRAY['gluten','vegan','vejetaryen']::text[]),
('acma',ARRAY['gluten','vegan','vejetaryen']::text[]),
('borek (peynirli)',ARRAY['gluten','sut','vejetaryen']::text[]),
('borek (kiymali)',ARRAY['gluten','vegan','vejetaryen']::text[]),
('su boregi',ARRAY['gluten','vegan','vejetaryen']::text[]),
('gozleme',ARRAY['gluten','vegan','vejetaryen']::text[]),
('lahmacun',ARRAY['gluten','vegan','vejetaryen']::text[]),
('pide (kiymali)',ARRAY['gluten','vegan','vejetaryen']::text[]),
('pide (kasarli)',ARRAY['gluten','vegan','vejetaryen']::text[]),
('pizza margarita',ARRAY['gluten','vegan','vejetaryen']::text[]),
('tost',ARRAY['gluten','vegan','vejetaryen']::text[]),
('kumpir',ARRAY['gluten','vegan','vejetaryen']::text[]),
('hamburger',ARRAY['et','gluten','kirmizi_et']::text[]),
('patates kizartmasi',ARRAY['gluten','vegan','vejetaryen']::text[]),
('beyaz peynir',ARRAY['sut','vejetaryen']::text[]),
('kasar peyniri',ARRAY['sut','vejetaryen']::text[]),
('lor peyniri',ARRAY['sut','vejetaryen']::text[]),
('tulum peyniri',ARRAY['sut','vejetaryen']::text[]),
('yogurt (tam yagli)',ARRAY['sut','vejetaryen']::text[]),
('yogurt (light)',ARRAY['sut','vejetaryen']::text[]),
('suzme yogurt',ARRAY['sut','vejetaryen']::text[]),
('kefir',ARRAY['sut','vejetaryen']::text[]),
('ayran',ARRAY['sut','vejetaryen']::text[]),
('sut (tam yagli)',ARRAY['sut','vejetaryen']::text[]),
('cacik',ARRAY['sut','vejetaryen']::text[]),
('zeytin (siyah)',ARRAY['vegan','vejetaryen','zeytin']::text[]),
('zeytin (yesil)',ARRAY['vegan','vejetaryen','zeytin']::text[]),
('bal',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('recel',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('tereyagi',ARRAY['sut','vejetaryen']::text[]),
('kaymak',ARRAY['sut','vejetaryen']::text[]),
('sucuk',ARRAY['et','kirmizi_et']::text[]),
('salam',ARRAY['et','kirmizi_et']::text[]),
('pastirma',ARRAY['et','kirmizi_et']::text[]),
('tahin',ARRAY['susam','vegan','vejetaryen']::text[]),
('pekmez',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('findik ezmesi',ARRAY['findik','vegan','vejetaryen']::text[]),
('cikolatali krema',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('coban salata',ARRAY['vegan','vejetaryen']::text[]),
('mevsim salata',ARRAY['vegan','vejetaryen']::text[]),
('gavurdagi salatasi',ARRAY['vegan','vejetaryen']::text[]),
('roka salatasi',ARRAY['vegan','vejetaryen']::text[]),
('kisir',ARRAY['gluten','vegan','vejetaryen']::text[]),
('haydari',ARRAY['sut','vejetaryen']::text[]),
('humus',ARRAY['susam','vegan','vejetaryen']::text[]),
('acili ezme',ARRAY['aci','vegan','vejetaryen']::text[]),
('patlican salatasi',ARRAY['vegan','vejetaryen']::text[]),
('atom',ARRAY['sut','vejetaryen']::text[]),
('piyaz',ARRAY['vegan','vejetaryen']::text[]),
('rus salatasi',ARRAY['sut','vejetaryen','yumurta']::text[]),
('fava',ARRAY['vegan','vejetaryen']::text[]),
('saksuka',ARRAY['vegan','vejetaryen']::text[]),
('cig kofte',ARRAY['aci','et','gluten','kirmizi_et']::text[]),
('baklava',ARRAY['findik','gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('kunefe',ARRAY['gluten','sut','vejetaryen','yuksek_seker']::text[]),
('sutlac',ARRAY['sut','vejetaryen','yuksek_seker']::text[]),
('kazandibi',ARRAY['sut','vejetaryen','yuksek_seker']::text[]),
('revani',ARRAY['gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('sekerpare',ARRAY['gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('tulumba tatlisi',ARRAY['gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('lokma',ARRAY['gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('asure',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('muhallebi',ARRAY['sut','vejetaryen','yuksek_seker']::text[]),
('profiterol',ARRAY['gluten','sut','vejetaryen','yuksek_seker','yumurta']::text[]),
('cheesecake',ARRAY['gluten','sut','vejetaryen','yuksek_seker','yumurta']::text[]),
('brownie',ARRAY['gluten','sut','vejetaryen','yuksek_seker','yumurta']::text[]),
('dondurma',ARRAY['sut','vejetaryen','yuksek_seker']::text[]),
('sufle',ARRAY['gluten','sut','vejetaryen','yuksek_seker','yumurta']::text[]),
('bitter cikolata',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('sutlu cikolata',ARRAY['sut','vejetaryen','yuksek_seker']::text[]),
('kurabiye',ARRAY['gluten','vejetaryen','yuksek_seker','yumurta']::text[]),
('kek (sade)',ARRAY['gluten','sut','vejetaryen','yuksek_seker','yumurta']::text[]),
('helva (tahin)',ARRAY['susam','vegan','vejetaryen','yuksek_seker']::text[]),
('elma',ARRAY['vegan','vejetaryen']::text[]),
('muz',ARRAY['vegan','vejetaryen']::text[]),
('portakal',ARRAY['vegan','vejetaryen']::text[]),
('mandalina',ARRAY['vegan','vejetaryen']::text[]),
('uzum',ARRAY['vegan','vejetaryen']::text[]),
('karpuz',ARRAY['vegan','vejetaryen']::text[]),
('kavun',ARRAY['vegan','vejetaryen']::text[]),
('cilek',ARRAY['vegan','vejetaryen']::text[]),
('kiraz',ARRAY['vegan','vejetaryen']::text[]),
('seftali',ARRAY['vegan','vejetaryen']::text[]),
('armut',ARRAY['vegan','vejetaryen']::text[]),
('kayisi',ARRAY['vegan','vejetaryen']::text[]),
('erik',ARRAY['vegan','vejetaryen']::text[]),
('nar',ARRAY['vegan','vejetaryen']::text[]),
('incir',ARRAY['vegan','vejetaryen']::text[]),
('ananas',ARRAY['vegan','vejetaryen']::text[]),
('kivi',ARRAY['vegan','vejetaryen']::text[]),
('avokado',ARRAY['vegan','vejetaryen']::text[]),
('kuru kayisi',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('kuru uzum',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('hurma',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('ceviz',ARRAY['findik','vegan','vejetaryen']::text[]),
('badem',ARRAY['findik','vegan','vejetaryen']::text[]),
('findik',ARRAY['findik','vegan','vejetaryen']::text[]),
('antep fistigi',ARRAY['findik','vegan','vejetaryen']::text[]),
('kaju',ARRAY['findik','vegan','vejetaryen']::text[]),
('yer fistigi',ARRAY['findik','vegan','vejetaryen']::text[]),
('ay cekirdegi',ARRAY['findik','vegan','vejetaryen']::text[]),
('kabak cekirdegi',ARRAY['findik','vegan','vejetaryen']::text[]),
('leblebi',ARRAY['findik','vegan','vejetaryen']::text[]),
('su',ARRAY['vegan','vejetaryen']::text[]),
('turk kahvesi (sade)',ARRAY['vegan','vejetaryen']::text[]),
('turk kahvesi (sekerli)',ARRAY['vegan','vejetaryen']::text[]),
('filtre kahve',ARRAY['vegan','vejetaryen']::text[]),
('latte',ARRAY['sut','vejetaryen']::text[]),
('cappuccino',ARRAY['sut','vejetaryen']::text[]),
('cay (sade)',ARRAY['vegan','vejetaryen']::text[]),
('cay (1 sekerli)',ARRAY['vegan','vejetaryen']::text[]),
('portakal suyu',ARRAY['vegan','vejetaryen']::text[]),
('kola',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('kola (sekersiz)',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('meyve suyu (kutu)',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('limonata',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('salgam suyu',ARRAY['aci','vegan','vejetaryen']::text[]),
('bira',ARRAY['alkol','vegan','vejetaryen']::text[]),
('sarap (kirmizi)',ARRAY['alkol','vegan','vejetaryen']::text[]),
('raki',ARRAY['alkol','vegan','vejetaryen']::text[]),
('smoothie',ARRAY['vegan','vejetaryen','yuksek_seker']::text[]),
('protein shake',ARRAY['vegan','vejetaryen']::text[]),
('cips',ARRAY['vegan','vejetaryen']::text[]),
('kraker',ARRAY['gluten','vegan','vejetaryen']::text[]),
('biskuvi',ARRAY['gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('granola bar',ARRAY['gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('yulaf ezmesi',ARRAY['gluten','vegan','vejetaryen']::text[]),
('musli',ARRAY['gluten','vegan','vejetaryen']::text[]),
('misir gevregi',ARRAY['gluten','vegan','vejetaryen','yuksek_seker']::text[]),
('popcorn',ARRAY['vegan','vejetaryen']::text[]),
('tavuk nugget',ARRAY['et','gluten']::text[]),
('pilav ustu tavuk',ARRAY['et']::text[]),
('tantuni',ARRAY['et','gluten','kirmizi_et']::text[]),
('kokorec',ARRAY['et','kirmizi_et','sakatat']::text[]),
('midye dolma',ARRAY['balik','et','kabuklu']::text[]),
('balik ekmek',ARRAY['balik','et','gluten','yuksek_seker']::text[]),
('kuru pasta',ARRAY['gluten','vejetaryen','yuksek_seker','yumurta']::text[]),
('waffle',ARRAY['gluten','vejetaryen','yuksek_seker','yumurta']::text[]),
('pankek',ARRAY['gluten','sut','vejetaryen','yuksek_seker','yumurta']::text[]),
('krep',ARRAY['gluten','vejetaryen','yuksek_seker','yumurta']::text[])
) as v(search_key, tags)
where f.search_key = v.search_key;
