-- Öğün rolleri ve kalite etiketleri (0020).
--
-- Üretici kategoriden rastgele kalem seçiyordu; sonuç "İskender + Kavurma +
-- Somon ızgara" gibi aynı öğünde ÜÇ ANA YEMEK oldu. Kategori bir yemeğin
-- öğündeki ROLÜNÜ söylemiyor: "et" kategorisinde hem ızgara tavuk hem sucuk
-- var, ikisi aynı şey değil.
--
-- Rol, öğün kompozisyonunun temeli: bir ana yemek + bir garnitür + bir
-- sebze/salata. İki ana yemek asla yan yana gelmez.
--
-- `keyfi` = plana OTOMATİK girmeyen kalemler: tatlılar, kızartmalar,
-- işlenmiş etler (sucuk, salam, pastırma), fast food, kaymak/bal gibi
-- katkılar. Kullanıcı elle günlüğüne ekleyebilir — biz ÖNERMİYORUZ.

update public.foods f
set role = v.role,
    tags = (select array(select distinct unnest(f.tags || v.extra)))
from (values
('mercimek corbasi','corba','{}'),
('ezogelin corbasi','corba','{}'),
('yayla corbasi','corba','{}'),
('tarhana corbasi','corba','{}'),
('domates corbasi','corba','{}'),
('tavuk suyu corba','corba','{}'),
('iskembe corbasi','corba','{}'),
('dugun corbasi','corba','{}'),
('brokoli corbasi','corba','{}'),
('mantar corbasi','corba','{}'),
('anali kizli corba','corba','{}'),
('yogurt corbasi','corba','{}'),
('izgara kofte','ana','{}'),
('sulu kofte','ana','{}'),
('inegol kofte','ana','{}'),
('kuru kofte','ana','{}'),
('tavuk sis','ana','{}'),
('tavuk izgara','ana','{}'),
('tavuk sote','ana','{}'),
('tavuk pirzola','ana','{}'),
('adana kebap','ana','{}'),
('urfa kebap','ana','{}'),
('beyti kebap','ana','{}'),
('iskender kebap','keyfi','{}'),
('doner (et)','keyfi','{}'),
('tavuk doner','keyfi','{}'),
('kuzu sis','ana','{}'),
('kuzu pirzola','ana','{}'),
('et sote','ana','{}'),
('kavurma','keyfi','{}'),
('tas kebabi','ana','{}'),
('hunkar begendi','ana','{}'),
('etli turlu','ana','{}'),
('karniyarik','ana','{}'),
('imambayildi','ana','{}'),
('musakka','ana','{}'),
('etli biber dolma','ana','{}'),
('zeytinyagli yaprak sarma','ana','{}'),
('etli yaprak sarma','ana','{}'),
('lahana sarma','ana','{}'),
('kabak dolma','ana','{}'),
('balik izgara','ana','{}'),
('hamsi tava','keyfi',ARRAY['kizartma']::text[]),
('somon izgara','ana','{}'),
('levrek izgara','ana','{}'),
('cupra izgara','ana','{}'),
('palamut izgara','ana','{}'),
('karides guvec','ana','{}'),
('kalamar tava','keyfi',ARRAY['kizartma']::text[]),
('kuru fasulye','ana','{}'),
('nohut yemegi','ana','{}'),
('barbunya pilaki','ana','{}'),
('mercimek yemegi','ana','{}'),
('etli nohut','ana','{}'),
('bakla yemegi','ana','{}'),
('turlu','ana','{}'),
('zeytinyagli taze fasulye','ana','{}'),
('zeytinyagli enginar','ana','{}'),
('zeytinyagli pirasa','ana','{}'),
('ispanak yemegi','ana','{}'),
('kabak yemegi','ana','{}'),
('karnabahar yemegi','ana','{}'),
('bamya yemegi','ana','{}'),
('patlican oturtma','ana','{}'),
('mucver','yan','{}'),
('menemen','kahvalti_protein','{}'),
('sahanda yumurta','kahvalti_protein','{}'),
('haslanmis yumurta','kahvalti_protein','{}'),
('omlet','kahvalti_protein','{}'),
('sucuklu yumurta','keyfi',ARRAY['islenmis_et']::text[]),
('pirinc pilavi','garnitur','{}'),
('bulgur pilavi','garnitur','{}'),
('sehriyeli pilav','garnitur','{}'),
('nohutlu pilav','garnitur','{}'),
('ic pilav','garnitur','{}'),
('kuskus','garnitur','{}'),
('makarna (domates soslu)','garnitur','{}'),
('firin makarna','keyfi','{}'),
('eriste','garnitur','{}'),
('manti','keyfi','{}'),
('spagetti bolonez','garnitur','{}'),
('beyaz ekmek','ekmek','{}'),
('tam bugday ekmegi','ekmek','{}'),
('cavdar ekmegi','ekmek','{}'),
('simit','keyfi','{}'),
('pogaca','keyfi','{}'),
('acma','keyfi','{}'),
('borek (peynirli)','ana','{}'),
('borek (kiymali)','ana','{}'),
('su boregi','keyfi','{}'),
('gozleme','ana','{}'),
('lahmacun','ana','{}'),
('pide (kiymali)','ana','{}'),
('pide (kasarli)','ana','{}'),
('pizza margarita','keyfi','{}'),
('tost','ana','{}'),
('kumpir','keyfi','{}'),
('hamburger','keyfi','{}'),
('patates kizartmasi','keyfi',ARRAY['kizartma']::text[]),
('beyaz peynir','kahvalti_protein','{}'),
('kasar peyniri','kahvalti_protein','{}'),
('lor peyniri','kahvalti_protein','{}'),
('tulum peyniri','kahvalti_protein','{}'),
('yogurt (tam yagli)','sut','{}'),
('yogurt (light)','sut','{}'),
('suzme yogurt','sut','{}'),
('kefir','sut','{}'),
('ayran','sut','{}'),
('sut (tam yagli)','sut','{}'),
('cacik','yan','{}'),
('zeytin (siyah)','kahvalti_yan','{}'),
('zeytin (yesil)','kahvalti_yan','{}'),
('bal','keyfi','{}'),
('recel','keyfi','{}'),
('tereyagi','keyfi','{}'),
('kaymak','keyfi','{}'),
('sucuk','keyfi',ARRAY['islenmis_et']::text[]),
('salam','keyfi',ARRAY['islenmis_et']::text[]),
('pastirma','keyfi',ARRAY['islenmis_et']::text[]),
('tahin','keyfi','{}'),
('pekmez','keyfi','{}'),
('findik ezmesi','keyfi','{}'),
('cikolatali krema','keyfi','{}'),
('coban salata','yan','{}'),
('mevsim salata','yan','{}'),
('gavurdagi salatasi','yan','{}'),
('roka salatasi','yan','{}'),
('kisir','yan','{}'),
('haydari','yan','{}'),
('humus','yan','{}'),
('acili ezme','yan','{}'),
('patlican salatasi','yan','{}'),
('atom','yan','{}'),
('piyaz','yan','{}'),
('rus salatasi','keyfi','{}'),
('fava','yan','{}'),
('saksuka','yan','{}'),
('cig kofte','keyfi','{}'),
('baklava','keyfi','{}'),
('kunefe','keyfi','{}'),
('sutlac','keyfi','{}'),
('kazandibi','keyfi','{}'),
('revani','keyfi','{}'),
('sekerpare','keyfi','{}'),
('tulumba tatlisi','keyfi',ARRAY['kizartma']::text[]),
('lokma','keyfi',ARRAY['kizartma']::text[]),
('asure','keyfi','{}'),
('muhallebi','keyfi','{}'),
('profiterol','keyfi','{}'),
('cheesecake','keyfi','{}'),
('brownie','keyfi','{}'),
('dondurma','keyfi','{}'),
('sufle','keyfi','{}'),
('bitter cikolata','keyfi','{}'),
('sutlu cikolata','keyfi','{}'),
('kurabiye','keyfi','{}'),
('kek (sade)','keyfi','{}'),
('helva (tahin)','keyfi','{}'),
('elma','meyve','{}'),
('muz','meyve','{}'),
('portakal','meyve','{}'),
('mandalina','meyve','{}'),
('uzum','meyve','{}'),
('karpuz','meyve','{}'),
('kavun','meyve','{}'),
('cilek','meyve','{}'),
('kiraz','meyve','{}'),
('seftali','meyve','{}'),
('armut','meyve','{}'),
('kayisi','meyve','{}'),
('erik','meyve','{}'),
('nar','meyve','{}'),
('incir','meyve','{}'),
('ananas','meyve','{}'),
('kivi','meyve','{}'),
('avokado','meyve','{}'),
('kuru kayisi','keyfi','{}'),
('kuru uzum','keyfi','{}'),
('hurma','keyfi','{}'),
('ceviz','kuruyemis','{}'),
('badem','kuruyemis','{}'),
('findik','kuruyemis','{}'),
('antep fistigi','kuruyemis','{}'),
('kaju','kuruyemis','{}'),
('yer fistigi','kuruyemis','{}'),
('ay cekirdegi','kuruyemis','{}'),
('kabak cekirdegi','kuruyemis','{}'),
('leblebi','kuruyemis','{}'),
('su','icecek','{}'),
('turk kahvesi (sade)','icecek','{}'),
('turk kahvesi (sekerli)','icecek','{}'),
('filtre kahve','icecek','{}'),
('latte','icecek','{}'),
('cappuccino','icecek','{}'),
('cay (sade)','icecek','{}'),
('cay (1 sekerli)','icecek','{}'),
('portakal suyu','icecek','{}'),
('kola','icecek','{}'),
('kola (sekersiz)','icecek','{}'),
('meyve suyu (kutu)','icecek','{}'),
('limonata','icecek','{}'),
('salgam suyu','icecek','{}'),
('bira','icecek','{}'),
('sarap (kirmizi)','icecek','{}'),
('raki','icecek','{}'),
('smoothie','icecek','{}'),
('protein shake','icecek','{}'),
('cips','keyfi',ARRAY['kizartma']::text[]),
('kraker','keyfi','{}'),
('biskuvi','keyfi','{}'),
('granola bar','keyfi','{}'),
('yulaf ezmesi','kahvalti_yan','{}'),
('musli','kahvalti_yan','{}'),
('misir gevregi','kahvalti_yan','{}'),
('popcorn','keyfi','{}'),
('tavuk nugget','keyfi',ARRAY['kizartma']::text[]),
('pilav ustu tavuk','keyfi','{}'),
('tantuni','keyfi','{}'),
('kokorec','keyfi','{}'),
('midye dolma','ana','{}'),
('balik ekmek','ana','{}'),
('kuru pasta','keyfi','{}'),
('waffle','keyfi','{}'),
('pankek','keyfi','{}'),
('krep','keyfi','{}')
) as v(search_key, role, extra)
where f.search_key = v.search_key;
